;************************************************************************
;* NBIOS10.Z80								*
;*									*
;* basiert auf der Version 3.1 1984 Rolf-Dieter Klein 841220            *
;* Ursprüngliche Version fuer 2 Mini und 2 Maxi Laufwerke		*
;*									*
;************************************************************************
;
; PLEASE NOTE THE CHANGED CP/M & BIOS START ADDRESS !!!
;
; 24.06.2026 *dg* Kommentare hinzugefuegt
;                 Binaer identisch zur Origial-Version
; 06.07.2026 *dg* V1.0 Erste Aenderungen am BIOS. Alte Monnitor-Routinen werden
;                 nicht mehr verwendet. Laufwerksumrechnung geaendert.
;                 Version getestet.
;                 Alle Aenderungen mit bedingter Assemblierung (Flag MINI3)
;                 Testweise den Speicherbereich fuer das BIOS auf E200..EFFF
;		  geaendert. CP/M startet dann bei CC00 (58K)
; 09.07.2026 *dg* V1.0 Erweitert um 4 IDE/CF-Laufwerke - funktioniert nicht
;                 System bootet aber Schreiben auf die IDE-Laufwerke schlaegt fehl.
; 12.07.2026 *dg* Lesen und Schreiben von CF funktioniert
; 31.07.2026 *dg* V1.0 Laufwerk C als HD Laufwerk konfiguriert (1.44 MB)
;                 Probleme immer beim ersten Scheiben nach dem Formatieren
; 02.08.2026 *dg* Laufwerk B: als 5.25 Zoll HD Laufwerk
;		  Funktioniert noch nicht, Format und Laufwerksparameter unklar 
; 03.08.2026 *dg* BIOS Debug-Ausgaben per Ctrl-A toggelbar
; 06.08.2026 *dg* 5.25 Zoll Format mit 1024*8 funktioniert (1.4 MB)
;                 5.25 Zoll Format mit 512*15 funktioniert! (1.2 MB)
; 08.08.2026 *dg* CF-Card Laufwerksparameter geaendert
; 09.08.2026 *dg* Quick'n dirty fix for Warmboot from IDE/CF
;		  (Disk-Parameter immer hardcodiert beim Warmboot aber konfigurierbar)
; 03.09.2026 *dg* Deblocking-Parameter fuer jedes Laufwerk stehen jetzt direkt hinter den
;		  DPBx Parameter-Bloecken                 
;
; Verbesserung/Veraenderungen zu BIOS 3.1 seit Juni 2026
;
; BIOS vergroessert, dadurch geaenderte Startadressen. CP/M ab CC00-E1FF,
; BIOS ab E200-EFFF.
; Dateinamen geaendert, die meisten Files und Tools beginnen mit "N" zu
; Unterscheidung von den Original-Files.
; Laufwerksparameter geaendert, A ist 800KB (NDR/NKC), B und C unterschiedlich,
; D ist IBM 8 Zoll SS/SD.
; IDE/CF eingebunden, Laufwerke E bis H, je 2 MB, E ist bootfaehig (geaenderte
; BIOS-Parameter).
; Blocking/Deblocking geaendert, ist jetzt flexibler und leichter zu
; konfigurieren max. Steprate wird beim Warmstart gesetzt.
; Debug-Ausgaben im BIOS ueber Compiler-Schalter und zur Laufzeit mit Ctrl-A
; ein- und ausschaltbar.
; Diverse Laufwerksformate gestestet, test mit echten 8 Zoll Laufwerken steht
; noch aus.
; MOVCPM und SYSGEN funktionieren werden der geaenderten BIOS-Groesse
; vermutlich nicht mehr und muessen angasst werden (oder flexible Variante
; verwenden).
;
; TO-DO:
; x Drive-spezifische Tabellen direkt bei den Laufwerkstabellen platzieren
;   (erledigt 03.09.26)
; - Maxi-Routinen in Mini-Routinen integrieren. Gemeinsame Routinen fuer
;   Blocking/Deblocking fuer alle Laufwerkstypen.
; x Make shure not to override the BIOS on WBOOT -> das war schon so
;   (CP/M Alteration Guide page 17)
;
;------------------------------------------------------------------------------

CPMVER	EQU 22		; CP/M version
FALSE	EQU 0
TRUE	EQU NOT FALSE
TEST	EQU TRUE
CR	EQU 0DH		; carriage return
LF	EQU 0AH		; line feed

;------------------------------------------------------------------------------
; Variant switches

; aktiviert alle bisherigen Aenderungen gegenueber der Originalversion 3.1
;DG01	EQU TRUE
DG_BHD	EQU FALSE	; drive B as HD drive (5 1/4 inch, 1.4 MB)
DG_CHD	EQU TRUE	; drive C as HD drive (3 1/2 inch, 1.44 MB)
DEBOUT	EQU TRUE	; debug outputs
BTDRV	EQU 0		; drive A:
;BTDRV	EQU 4		; drive E: (IDE/CF)

; logical drive to boot from
	; boot from disk A (800KB NDE/NKC format)
	IF BTDRV = 0	; drive A
BTSEC	EQU 8		; start sector of CP/M on disk with 1024 bytes/sector
BTSECN	EQU 40		; sector per track
	ENDIF
	
	; boot from IDE/CF (2 MB format)
	IF BTDRV = 4	; drive E
BTSEC	EQU 1		; start sector of CP/M on IDE/CF (second sector)
BTSECN	EQU 64		; sector per track
	ENDIF

;------------------------------------------------------------------------------
; Monitor functions

MCONOUT	EQU 0F009h	; character in C

;------------------------------------------------------------------------------
; CPM and BIOS sizes and addresses

MSIZE 	EQU 58			; actual memory size of this BIOS (58K)
;MSIZE 	EQU 59			; actual memory size of this BIOS (58K)
;MSIZE 	EQU 60			; default memory size model (60K)

BIAS	EQU (MSIZE - 20) * 1024	; smallest memory model is 20K
CCP	EQU 3400H + BIAS	; start of CCP (CP/M), smallest memory model starts at 3400h
BDOS	EQU CCP + 806H		; BDOS entry behind 6 byte serial number, size of CCP is 800h
CPML	EQU 1600H		; length of CP/M (CCP + BDOS)
BIOS	EQU CCP + CPML		; start of BIOS

BDOSADR	EQU BDOS - 6		; actual start address of BDOS (used for patches)

CPMB	EQU CCP			; CP/M boot entry

NSECTS	EQU CPML / 128		; Number of logical sectors ocupied by CP/M
				; (used for for WBOOT)

;-----------------------------------------------------------------------------

JWARM	EQU 0000H	; JMP to WBOOT
IOBYTE	EQU 0003H	; Address of IOBYTE
CDISK	EQU 0004H	; Address of last used drive and user (low-nibble: current drive, high-nibble: current user)
JBDOS	EQU 0005H	; JMP to BDOS
JRST7	EQU 0038H	; JMP RST7 (7*8)
BUFF	EQU 0080H	; buffer address
RETRY	EQU 5		; Fehlerversuche bei BOOT und Maxi Read/Write

;-----------------------------------------------------------------------------

	ORG BIOS	; regular start of BIOS
	;ORG BIOS-4000H	; for debugging

STARTBIOS:

	JP BOOT		; Cold boot

	; --- start of offical BIOS calls ---
	
WBOOTE:	JP WBOOT	; Warm boot (CTRL-C)
	JP CONST	; Get CONSOLE status -> A, 0FFh if character available
	JP CONIN	; Input character from CONSOLE -> A
	JP CONOUT	; Output character to CONSOLE (C)
	JP LIST		; Output character to LIST device (C)
	JP PUNCH	; Output character to PUNCH device (C)
	JP READER	; Input character from READER device -> A

	JP HOME		; Select track home position (no execution)
	JP SELDSK	; Select drive, drive 0..n-1 in C, returns disk parameter header block in HL
	JP SETTRK	; Select track for read/write, track in C (logic tracks!!! e.g. 0..159)
	JP SETSEC	; Select sector for read/write, sector in C (logic sectors!!! e.g. 0..39)
	JP SETDMA	; Set disk read/write address (no real DMA), address in BC
	JP READ		; Read sector
	JP WRITE	; Write sector
	JP LISTST	; Listener ready? (not implemented, returns 1 = not ready)
	JP SECTRAN	; sector translation (skew only)
	
	; --- end of offical BIOS calls ---
	
	;JP FLUSH	; BDOS close and write sector buffer to disk (not used)

;-----------------------------------------------------------------------------

	; size of mini disks A, B, C
	; TRUNC(5 logical sectors * 1024 logical sector size * (2*80 tracks - 4 offset) / 2048 block size) - 1 = ca. 780 KB
	; TRUNC (5 * 1024 * (160-4)/2048) - 1 = ca. 780 K

	;DISKS 8		; define 8 drives (A..H)
NDISKS	EQU	8	

DPBASE	EQU	$		;BASE OF DISK PARAMETER BLOCKS

DPE0:	DW	XLT0,0000H	;TRANSLATE TABLE
	DW	0000H,0000H	;SCRATCH AREA
	DW	DIRBUF,DPB0	;DIR BUFF,PARM BLOCK
	DW	CSV0,ALV0	;CHECK, ALLOC VECTORS

DPE1:	DW	XLT1,0000H	;TRANSLATE TABLE
	DW	0000H,0000H	;SCRATCH AREA
	DW	DIRBUF,DPB1	;DIR BUFF,PARM BLOCK
	DW	CSV1,ALV1	;CHECK, ALLOC VECTORS

DPE2:	DW	XLT2,0000H	;TRANSLATE TABLE
	DW	0000H,0000H	;SCRATCH AREA
	DW	DIRBUF,DPB2	;DIR BUFF,PARM BLOCK
	DW	CSV2,ALV2	;CHECK, ALLOC VECTORS

DPE3:	DW	XLT3,0000H	;TRANSLATE TABLE
	DW	0000H,0000H	;SCRATCH AREA
	DW	DIRBUF,DPB3	;DIR BUFF,PARM BLOCK
	DW	CSV3,ALV3	;CHECK, ALLOC VECTORS

DPE4:	DW	0000h, 0000h
	DW	0000h, 0000h
	DW	DIRBUF, DPB4
	DW	CSV4, ALV4

DPE5:	DW	0000h, 0000h
	DW	0000h, 0000h
	DW	DIRBUF, DPB5
	DW	CSV5, ALV5

DPE6:	DW	0000h, 0000h
	DW	0000h, 0000h
	DW	DIRBUF, DPB6
	DW	CSV6, ALV6

DPE7:	DW	0000h, 0000h
	DW	0000h, 0000h
	DW	DIRBUF, DPB7
	DW	CSV7, ALV7

	; Disk 0 (A) ---------------------------------------------------------
	
	; *** DISKDEF BEDEUTUNG DER PARAMETER***
	; 0 = NUMMER DES LAUFWERKS
	; 0 = NUMMER DES ERSTEN SEKTORS EINER SPUR
	; 39 =  NUMMER DES LETZTEN SEKTORS EINER SPUR
	; 0 = OPTIONALER VERSCHIEBUNGSFAKTOR ZUM
	;     VERSETZEN ABSPEICHERN DER SEKTOREN
	; 2048 = GROESSE EINES BLOCKS
	; 389 = ZAHL DER MAX. MOEGLICHEN BLOECKE
	; 256 = ZAHL DER DIRECTORY EINTRITTSPUNKTE
	; 256 = ZAHL DER GEPRUEFTEN EINTRITTSPUNKTE
	; OFFS = ADDITIVE KONSTANTE ZUM ANSPRECHEN DER SPUR 00

	; physical format: 3,5 inch NKC, DD, DS, 1024 bytes/sector, 5 sectors/track, 80 tracks
	; DISKDEF 0,0,39,0,2048,389,256,256,4
DPB0	EQU	$	; DISK PARM BLOCK
	DW	40	; SEC PER TRACK
	DB	4	; BLOCK SHIFT
	DB	15	; BLOCK MASK
	DB	0	; EXTNT MASK
	DW	388	; DISK SIZE-1
	DW	255	; DIRECTORY MAX
	DB	240	; ALLOC0
	DB	0	; ALLOC1
	DW	64	; CHECK SIZE
	DW	4	; OFFSET
	; new parameters:
	DB	00100000B ; Mini/DD
	DB 	3	  ; 40 / 5 Tracks = 8 -> 2^3
	DB	00000111B ; 1024 bytes/sector -> modulo 0..7
	
XLT0	EQU	0	; NO XLATE TABLE

	IF NOT DG_BHD

	; Disk 1 (B), same as Disk A -----------------------------------------
	; DISKDEF 1,0	; LAUFWERK 1 WIE LAUFWERK 0 DEFINIERT
DPB1	EQU	DPB0	; EQUIVALENT PARAMETERS
XLT1	EQU	XLT0	; SAME TRANSLATE TABLE

	ELSE

	IF FALSE
	; Disk 1 (B): PHYSICAL FORMAT: 1.4 MB, HD, DS, 1024 BYTES/SECTOR, 4096 Bytes/Block, 8 SECTORS/TRACK, 80 TRACKS
 DPB1	EQU	$	; DISK PARM BLOCK
 	DW	60	; SEC PER TRACK
 	DB	5	; BLOCK SHIFT
 	DB	31	; BLOCK MASK
 	DB	1	; EXTNT MASK
 	DW	354 ;315; 275	; DISK SIZE-1
  	DW	255	; DIRECTORY MAX
 	DB	192	; ALLOC0
 	DB	0	; ALLOC1
 	DW	64	; CHECK SIZE
 	DW	2	; OFFSET
	; new parameters:
	DB	00000000B ; Maxi/HD
	DB 	2	  ; 60 / 15 = 4 -> 2^2
	DB	00000011B ; 512 bytes/sector -> modulo 0..3

 XLT1	EQU	0	; NO XLATE TABLE
 
	ENDIF	; FALSE

	; Disk 1 (B): PHYSICAL FORMAT: 1.2 MB, HD, DS, 512 BYTES/SECTOR, 4096 Bytes/Block, 15 SECTORS/TRACK, 80 TRACKS
 DPB1	EQU	$	; DISK PARM BLOCK
 	DW	60	; SEC PER TRACK
 	DB	5	; BLOCK SHIFT
 	DB	31	; BLOCK MASK
 	DB	1	; EXTNT MASK
 	;DW	275 ; 295	; DISK SIZE-1
 	DW	295	; DISK SIZE-1
  	DW	255	; DIRECTORY MAX
 	DB	192	; ALLOC0
 	DB	0	; ALLOC1
 	DW	64	; CHECK SIZE
 	DW	2	; OFFSET
	; new parameters:
	DB	00000000B ; Maxi/HD
	DB 	2	; 60 / 15 = 4 -> 2^2
	DB	00000011B ; 512 bytes/sector -> modulo 0..3

 XLT1	EQU	0	; NO XLATE TABLE

	ENDIF

	IF NOT DG_CHD

	; Disk 2 (C), same as Disk A -----------------------------------------

	; DISKDEF 2,0	; LAUFWERK 2 WIE LAUFWERK 0 DEFINIERT
DPB2	EQU	DPB0	; EQUIVALENT PARAMETERS
XLT2	EQU	XLT0	; SAME TRANSLATE TABLE

	ELSE

	; Disk 2 (C): PHYSICAL FORMAT: 1.44 MB, HD, DS, 1024 BYTES/SECTOR, 4096 Bytes/Block, 9 SECTORS/TRACK, 80 TRACKS
 DPB2	EQU	$	; DISK PARM BLOCK
 	DW	72	; SEC PER TRACK
 	DB	5	; BLOCK SHIFT
 	DB	31	; BLOCK MASK
 	DB	1	; EXTNT MASK
 	DW	354	; DISK SIZE-1
  	DW	255	; DIRECTORY MAX
 	DB	192	; ALLOC0
 	DB	0	; ALLOC1
 	DW	64	; CHECK SIZE
 	DW	2	; OFFSET
	; new parameters:
 	DB	00000000B ; Maxi/HD
	DB 	2	  ; 72 / 9 = 8 -> 2^3
	DB	00000011B ; 512 bytes/sector -> modulo 0..3
	
 XLT2	EQU	0	; NO XLATE TABLE
	
	ENDIF


	; Disk 3 (D) --------------------------------------------------------
	; physical format: 8 inch, SD, SS, 128 bytes/sector, 26 sectors/track, 77 tracks
	; DISKDEF 3,1,26,6,1024,243,64,64,2 ; 8 ZOLL DEFINITION

DPB3	EQU	$	; DISK PARM BLOCK
 	DW	26	; SEC PER TRACK
 	DB	3	; BLOCK SHIFT
 	DB	7	; BLOCK MASK
 	DB	0	; EXTNT MASK
 	DW	242	; DISK SIZE-1
 	DW	63	; DIRECTORY MAX
 	DB	192	; ALLOC0
 	DB	0	; ALLOC1
 	DW	16	; CHECK SIZE
 	DW	2	; OFFSET
	; new parameters:
	DB	00010000B ; Maxi/SD
	DB	0	; no deblocking
	DB	0	; no deblocking
	
XLT3	EQU	$	; TRANSLATE TABLE
 	DB	1		
 	DB	7		
 	DB	13		
 	DB	19		
 	DB	25		
 	DB	5		
 	DB	11		
 	DB	17		
 	DB	23		
 	DB	3		
 	DB	9		
 	DB	15		
 	DB	21		
 	DB	2		
 	DB	8		
 	DB	14		
 	DB	20		
  	DB	26		
 	DB	6		
 	DB	12		
 	DB	18		
 	DB	24		
 	DB	4		
 	DB	10		
 	DB	16		
 	DB	22	

	; Disk 4 (E), IDE partition 0 ----------------------------------------
DPB4:	;disk parameter block for all disks.
	IF FALSE
	; Disk size 2 mb, DSM 1023, yields 256 tracks (0 to 255)
	DW	64	; sectors per track
	DB	4	; block shift factor
	DB	15	; block mask - with block shift, sets block size to 1024
	DB	0	; null mask
	DW	1023	; disk size-1 = number of blocks in a disk - 1
	DW	256	; directory max = no. directory entries/disk, arbitrary
	DB	240	; alloc 0 -- need 4 bits (blocks) for 256 directory entries -- 
	DB	0	; alloc 1 -- no. bits = (directory max x 32)/block size	
	DW	0	; check size -- no checking, so zero
	DW	1	; track offset -- first track for system
	ELSE
	; Disk size 2 MB, 128 Byte/Sector, 64 sectors, 256 tracks (0 to 255), Blocksize 4096
	; DISKDEF 0,1,64,0,4096,510,256,0,1
	DW	64	; sectors per track
	DB	5	; block shift factor
	DB	31	; block mask - with block shift, sets block size to 1024
	DB	1	; null mask
	DW	509	; disk size-1 = number of blocks in a disk - 1
	DW	255	; directory max = no. directory entries/disk, arbitrary
	DB	192	; alloc 0 -- need 4 bits (blocks) for 256 directory entries -- 
	DB	0	; alloc 1 -- no. bits = (directory max x 32)/block size	
	DW	0	; check size -- no checking, so zero
	DW	1	; track offset -- first track for system
	ENDIF

	; Disk 5 (F), IDE partition 1 ----------------------------------------
DPB5	EQU	DPB4	; EQUIVALENT PARAMETERS

	; Disk 6 (G), IDE partition 2 ----------------------------------------
DPB6	EQU	DPB4	; EQUIVALENT PARAMETERS

	; Disk 7 (H), IDE partition 3 ----------------------------------------
DPB7	EQU	DPB4	; EQUIVALENT PARAMETERS

;-----------------------------------------------------------------------------
; CP/M message after cold start

SIGNON:	DB 26
	DB CR,LF,'CP/M '
	DB CPMVER/10+'0','.',CPMVER MOD 10+'0'
	DB ' for MC-Computer '
	DB MSIZE/10+'0',MSIZE MOD 10+'0'
	DB 'K NBIOS 260904-01'
	DB " BOOT=",BTDRV+'A',CR,LF

	DB "A:NKC800"

	IF NOT DG_BHD
	DB ",B:NKC800"
	ELSE
	DB ",B:1.4MB"
	ENDIF

	IF NOT DG_CHD
	DB ", C:NKC800"
	ELSE
	DB ",C:1.44MB"
	ENDIF

	DB ",D:IBM SS/SD,E..H:IDE"

	DB CR,LF,0

;-----------------------------------------------------------------------------
; get state of CONSOLE (if character is available)

CONST:	JP 0F012H

;-----------------------------------------------------------------------------
; read one char from CONSOLE and clears parity bit

CONIN:	CALL 0F003H
	AND 7FH

	IF DEBOUT

	CP A,1
	RET NZ

	; toggle debug
	LD B,A
	LD A,(DEBACT)
	XOR A,01H
	LD (DEBACT),A
	LD A,B

	ENDIF
	
	RET

;-----------------------------------------------------------------------------
; read one char from READER device -> A

READER	EQU 0F006H

;-----------------------------------------------------------------------------
; write one char to CONSOLE (C)

CONOUT	EQU 0F009H

;-----------------------------------------------------------------------------
; write one char to PUNCH device (C)

PUNCH	EQU 0F00CH

;-----------------------------------------------------------------------------
; write one char to LIST device (C)			

LIST	EQU 0F00FH

;-----------------------------------------------------------------------------
; restart Monitor

MSTART	EQU 0F01EH

;-----------------------------------------------------------------------------
; Monitor warm start

MWARM	EQU 0F033H	; Monitor warm start, will be overwritten by BIOS

;-----------------------------------------------------------------------------
; Monitor write string

MWRSTR	EQU 0F036H	; Write string, will be overwritten by BIOS

;-----------------------------------------------------------------------------
; Cold boot

BOOT:	LD SP,BUFF+80H	; set stack

	LD HL,SIGNON	; output start message
	CALL PRMSG
	
	; clear / set last used drive
	LD A,BTDRV
	LD (CDISK),A
	
	; sector buffer is empty, set to physical sector buffer not changed
	XOR A
	LD (BUFCHG),A
	
	; drive is undefined
	LD A,0FFH
	LD (CURDRV),A

	; disable monitor entries, set to WBOOT
	LD HL,WBOOT
	LD (MWARM+1),HL
	LD (MWRSTR+1),HL
	
	;CALL PATF	; patch BDOS close function
	CALL PATA	; patch BDOS active drive
	;CALL PATB

	; set steprate
	LD D,00000000B	; max steprate 00b, no sso
	LD B,0		; set steprate
	CALL FEXEC
	
	JP GOCPM	; start CP/M

;-----------------------------------------------------------------------------
; Warm boot

WBOOT:	; write physical sector buffer to disk if changed
	LD A,(BUFCHG)
	OR A
	JP Z,WBOO1

	CALL PUTPHS	; normalerweise ist Schreibvorgang
			; nach einem Direktoryzugriff abgeschlossen
			; ACHTUNG BUG!? PUTPHS nur fuer Mini/DD-Laufwerke
			; Bei einem anderen Laufwerk geht das wohl schief
			
WBOO1:	LD A,0FFH	; alle Tracks ungueltig, bei Diskettenwechsel wichtig
	LD (CURDRV),A

	LD SP,BUFF	; Stack zuweisen
	LD C,RETRY	; Anzahl der Versuche
	PUSH BC		; und dann anfangen zu booten

WBOO2:	; loop, load CP/M
	LD BC,CPMB	; Init load address to CPM start address
	CALL SETDMA
	LD C,BTDRV	; drive 0 (or BTDRV)
	CALL SELDSK
	LD C,0		; track 0
	CALL SETTRK
	LD C,BTSEC	; start with first logical sector behind physical boot sector
	CALL SETSEC	; (depends on the number of logical sectors per phyiscal sector)
	POP BC
	LD B,NSECTS	; number of sectors for CP/M without BIOS, do not overwrite BIOS
			; to preserve patches.

	;LD C,'1'
	;CALL CONOUT

WBOO3:	; sector read loop
	PUSH BC
	CALL READ	; read logical secor
	JP NZ,BOOTERR	; -> error
	
	LD HL,(IOD)	; increment DMA address by 128
	LD DE,128
	ADD HL,DE
	LD (IOD),HL
	LD A,(IOS)	; check for end of track
	CP BTSECN-1
	JP C,WBOO4

	; next track, Caution! track scheme is hardcoded !!!
	LD A,(IOT)	; increment track
	INC A	  	; jedoch im Verfahren 0,2,...
	INC A		; SPUR 0, dann SPUR 2, wegen BOOT.ASM
	LD (IOT),A	; denn 1,3,5 ist die Rueckseite des Laufwerks
	LD A,0FFH	; 0,1,2,3.... will by incremented to 0
	
WBOO4:	INC A
	LD (IOS),A	; set new sector
	
	POP BC		; Schleifenzaehler zuruech
	DEC B		; und immer weiter lesen
	JP NZ,WBOO3	; -> read next sector
	
	;---------------------------------------------------------------------

GOCPM:	LD BC,BUFF	; Buffer auf Default einstellen
	CALL SETDMA	; so wie es CP/M braucht
	
	LD A,0C3H	; Sprung auf den WARM-Boot im
	LD (JWARM),A	; RAM ablegen.
	LD HL,WBOOTE	; Warm-Boot-Adresse
	LD (JWARM+1),HL	; nicht vergessen
	
	LD (JBDOS),A	; Sprung auf die BDOS-CALL-Adresse
	LD HL,BDOS	; legen und auch das Ziel
	LD (JBDOS+1),HL	; dorthin
	
	LD (JRST7),A	; RST7 definieren, default ist Monitor
	LD HL,MSTART	; der aber normalerweise kurzgeschl. ist.
	LD (JRST7+1),HL		
	
	; clear / set last used drive
	;LD A,BTDRV
	;LD (CDISK),A
	;CALL PATF	; patch BDOS close function
	CALL PATA	; patch BDOS active drive
	;CALL PATB
	
	LD A,(CDISK)	; das zuletzt verwendete Laufwerk
	LD C,A		; laden und damit selektieren.
	JP CPMB

	;---------------------------------------------------------------------

BOOTERR:		; im Fehlerfalle, bei BAD-Sektor.
	POP BC		; erst mal nocheinmal versuchen
	DEC C
	JP Z,BOOTE0	; bis hoffnungslos, dann Fehlermeldung
	
	PUSH BC
	JP WBOO2	; -> try again

BOOTE0:	; Fehlermeldung ausgeben und Monitor neu starten, bzw. WBOOT
	LD HL,ERRMSG
	CALL PRMSG
	JP MSTART

ERRMSG:	; Fehlermeldung
	DB '?BOOT',0

;-----------------------------------------------------------------------------
; List status (used by BDOS)
; LST state, not used

LISTST:	NOP
	XOR A		; 0 = not ready
	RET

;-----------------------------------------------------------------------------
; Home drive (used by BDOS)

HOME:	LD C,0		; aber nur anwaehlen, nicht
	JP SETTRK	; ausfuehren

;-----------------------------------------------------------------------------
; Select disk (used by BDOS)
; drive-code in C (0..3)

SELDSK:	LD HL,0		; und pruefen ob gueltig
	LD A,C		; wenn groesser als ndisks
	CP NDISKS	; dann nicht ok
	RET NC		; Nummer 0 bis n-1 erscheint in A
	
	LD (DBANK),A

	;POP HL
	;PUSH HL
	;CALL DEBSEL

	; get address of DPEx -> HL (= DPBASE + disk number * 16)
	LD L,C		; disk number
	LD H,0
	ADD HL,HL	; HL <- HL * 16
	ADD HL,HL	
	ADD HL,HL	
	ADD HL,HL	
	LD DE,DPBASE	; add DPBASE
	ADD HL,DE

	; get additional deblockling parameters from the end of
	; the regluar DPBx block
	PUSH HL
	LD DE,10	; position of DPBx in DPEx
	ADD HL,DE
	LD E,(HL)
	INC HL
	LD D,(HL)
	EX DE,HL	; address of DPEx now in HL
	LD DE,15	; length of DPBx
	ADD HL,DE
	LD A,(HL)
	LD (BLREG),A
	INC HL
	LD A,(HL)
	LD (BLPOW),A
	INC HL
	LD A,(HL)
	LD (BLMSK),A
	POP HL

	RET

;-----------------------------------------------------------------------------
; Select track (used by BDOS)
; track in C

SETTRK:	LD HL,IOT
	LD (HL),C
	RET

;-----------------------------------------------------------------------------
; Select sector  (used by BDOS)
; sector in C

SETSEC:	LD HL,IOS
	LD (HL),C
	RET

;-----------------------------------------------------------------------------
; Sector translation (used by BDOS)
; sector in C
; skew table in DE (or 0)
; write calculated sector to IOS and L

SECTRAN:LD A,D		; check if skew table != 0
        OR E
        JP Z,SECTR1	; =0, -> no skew

	; calc sector offset into skew table
	LD B,0
	EX DE,HL
	ADD HL,BC	; sector in C
	LD A,(HL)	; load skew value
	LD (IOS),A	; save in IOS 
	LD L,A		; and in L
        LD H,0		; was missing *dg* 27.07.2026
	RET

SECTR1:	; no skew, return sector
	LD L,C		; sector in C
        LD A,C
        LD (IOS),A	; save in IOS
        LD H,0
        RET

;-----------------------------------------------------------------------------
; Set DMA address (used by BDOS)
; address in BC

SETDMA:	LD L,C
	LD H,B
	LD (IOD),HL
	RET

;-----------------------------------------------------------------------------
; 0-terminerte Text ausgaben, Adresse in HL

PRMSG: 	LD A,(HL)
	OR A
	RET Z		; -> end of text
	
	PUSH HL
	LD C,A
	CALL CONOUT
	POP HL
	INC HL
	JP PRMSG	; -> next char

;=============================================================================
; Read and write sector using FEXEC into monitor

;-----------------------------------------------------------------------------
; Read sector

; Buffer (DMA address) in IOD
; Drive in DBANK (0..n-1)
; Track in IOT (0..n-1 * side)
; Sector in IOS (0..n-1)

READ:
	;POP HL
	;PUSH HL
	;CALL DEBDRV	; debug output (DBANK)

	LD A,(DBANK)	; drive 0..5
	CP 3
	JP C,MINIRD	; A < 3 -> drive 0,1,2 (Mini disks)
	
	CP 4
	JP C,MAXIRD	; A < 4 -> drive 3 (Maxi disks)

	;---------------------------------------------------------------------
	; A >= 5, Read RAM disk

	CP 8
	JP C,IDERD	; A < 8 -> IDE disks 4,5,6,7
	
	; error
	LD A,1		; Fehler da, Bank nicht vorhanden,
	RET		; wirkt wie BAD-Sektor

	;---------------------------------------------------------------------
	
NOERR:	XOR A		; sonst ok.
	RET

	;---------------------------------------------------------------------
	; Calculate address for ram disk, source in HL
	; SEKTOR 0..E,  TRAck 0..5fh
	; SSSSTTTT T0000000   , adresse fuer RAM-Floppy
ADRERZ:	LD A,(IOT)		; Track holen
 	RRCA 			; und umrechnen
 	AND 0FH			; unterer Teil vom MSB
 	LD H,A
 	LD A,(IOS)		; dann Sektor dazu
 	RLCA
 	RLCA
 	RLCA
 	RLCA
 	AND 0F0H
 	OR H
 	LD H,A			; damit sssstttt ok
 	LD A,(IOT)
 	RRCA			; txxxxxxx
 	AND 80H
 	LD L,A			; t0000000
 	LD A,(IOT)		; nun noch bank bestimmen, in c und b	
 	RLCA			; und dazu msb-Teil des Tracks verwenden
 	RLCA			; 0mmttttt
 	RLCA			; Banknummer
 	AND 03H			; 000000mm
	ADD A,1			; erst ab Bank 1 starten
 	LD B,A			; da BANK 0=CP/M RAM und TPA
 	LD C,A			; ok beide definiert
 	RET

;-----------------------------------------------------------------------------
  
; Umrechnen fuer Maxi fuer neue Monitor Floppy-Routine
; drive-code -> C

MAXCAL:	; drive A,B,C,D -> 0001,0010,0100,1000
	LD A,(DBANK)	; 0..3
	INC A		; -> 1..4
	LD B,A
	SCF		; shift in carry
MAXC2:	RLA
	DJNZ MAXC2
	
	LD B,A
	LD A,(BLREG)
	OR B
	LD C,A

	LD A,(DBANK)
	CP 4
	JP NZ,MAXC3
	
	; drive E, side 1
	LD A,C
	OR 10000000B
	LD C,A

MAXC3:	RET

;-----------------------------------------------------------------------------
; Read Maxi disk

MAXIRD:	LD B,RETRY	; Anzahl der Leseversuche

MAXIR1:	; retry loop
	PUSH BC		; dann ausfuehren
	LD HL,(IOD)	; Zieladresse holen
	LD A,(IOT)	; Spurnummer
	LD D,A	
	LD A,(IOS)	; Sektornummer
	LD E,A
	LD B,1		; Lese-Befehlscode
	CALL MAXCAL	; vorher Laufwerkscode umrechnen
	CALL FEXEC	; und dann ausfuehren
	POP BC		; Retry-Zaehler
	RET Z		; kein Fehler, dann ok zurueck
	DEC B		; sonst nochmals probieren
	JP NZ,MAXIR1	; -> retry		
	
	LD A,1		; BAD SEKTOR
	OR A
	RET

;-----------------------------------------------------------------------------
; Write sector using FEXEC into monitor

; Buffer (DMA address) in IOD
; Drive in DBANK (0..n-1)
; Track in IOT (0..n-1)
; Sector in IOS (0..n-1)
; BDOS-Flag in C (0 = standard sector, 1 = directory sector, 2 =  first sector in block)

WRITE:	
	IF DEBOUT
	;LD A,1		; WRITE
	;CALL DEBBUF

	;POP HL
	;PUSH HL
	;CALL DEBDRV	; debug output (DBANK)
	ENDIF


	LD A,(DBANK)	; drive 0..5
	CP 3
	JP C,MINIWR	; A < 3 -> drive 0,1,2 (Mini disks)
	
	CP 4
	JP C,MAXIWR	; A < 4 -> drive 3 (Maxi disks)
	
	;---------------------------------------------------------------------
	
	CP 8
	JP C,IDEWR	; A < 8 -> IDE disks 4,5,6,7
	
	LD A,1		; Fehler ausgeben
	RET

	;---------------------------------------------------------------------
	; Write Maxi disk

MAXIWR:	LD B,RETRY

MAXIW1:	PUSH BC		; Dazu Fehlerzaehler retten

	LD HL,(IOD)	; Quelleadresse laden
	
	LD A,(IOT)	; Spur
	LD D,A
	
	LD A,(IOS)	; Sektor
	LD E,A
	
	LD B,2		; Schreib-Befehlscode
	CALL MAXCAL	; vorher Laufwerk umrechnen
	CALL FEXEC	; und ausfuehren
	POP BC	
	RET Z		; -> no error
	
	DEC B
	JP NZ,MAXIW1	; -> retry
	
	LD A,1		; bad sector
	OR A
	RET

;-----------------------------------------------------------------------------
; Flush current sector buffer

	IF FALSE

FLUSH:	; BDOS close file
	JP BDOSADR + 08A2H

	; write sector buffer to disk if changed
	LD A,(BUFCHG)
	OR A
	RET Z
	JP PUTPHS

	ENDIF	; FALSE

;=============================================================================
; Read Mini disk, 80 Spur, DD, DS

;READ und WRITE unter Verwendung von MEXEC
; HL=DMA ADR
; DE=TRACK/SECTOR
; B=0 RSTORE
;   1 READ
;   2 WRITE
; C=DRIVE 0...3  10H,11H,12H,13H  DOUBMIN 0D0H,0D1H,0D2H,0D3H
;                                          A   C    B    D

PHSBUF	EQU 0FC00H	; Memory area of interactive Monitor for logical sector (1K)

;-----------------------------------------------------------------------------
; Calculates physical drive from DBANK and IOT -> C
; only for Mini disks

; DBANK, IOT     C
;  0     F    -> 0
;  1     F    -> 2
;  0     B    -> 1
;  1     B    -> 3

; muss fuer Minidisk C und D erweitert werden

; drive number (0..n-1) -> C, Bit 0..3
; side -> (0..n-1) -> C, Bit 7

; calculates physical sector from logical sector, IOS -> E
; logical sector 0..39 -> physical sector 1..5

; calculates logical track from physical track, IOT -> D
; 0..159 -> 0..79 (max 127)

MINCAL:	; logical sector to physical sector
	; get drive specific factor
	LD A,(BLPOW)
	AND A
	JR Z,MINIC4	; -> factor = 0

	LD B,A		; factor
	LD A,(IOS)	; logical sector
MINIC2:	SRL A
	DJNZ MINIC2
	
	JR MINIC5

MINIC4:	; factor = 0
	LD A,(IOS)

MINIC5:	INC A		; sector number starts with 1
	LD E,A		; save in E

	; drive A,B,C,D -> 0001,0010,0100,1000
	LD A,(DBANK)	; 0..3
	INC A		; -> 1..4
	LD B,A
	XOR A
	SCF		; shift in carry
MINIC6:	RLA
	DJNZ MINIC6

	LD B,A
	LD A,(BLREG)
	OR B
	LD C,A

	LD A,(IOT)
	SRL A		; Track / 2, Bit0 -> Carry (side 1)
	LD D,A		; Track merken
	JP NC,MINIC7	; -> side 0

	; side
	LD A,C
	OR 10000000B	; side 1 flag
	LD C,A
	
MINIC7:	; D=track=D, E=sector, C=drive-code + side
	RET

;-----------------------------------------------------------------------------
; Lookup table, table in HL, offset in A

	IF FALSE

LOOKUP:	PUSH DE
	LD E,A
	LD D,0
	ADD HL,DE
	LD A,(HL)
	POP DE
	RET
	
	ENDIF
	
;-----------------------------------------------------------------------------
; Read Mini disk
; DBANK, IOT, IOS,

MINIRD:	CALL MINCAL	; calc physical drive and sector data for compare

	LD A,(CURDRV)
	CP C		; compare drive + side
	JP NZ,MINIR2	; -> drive not equal, load sector
	
	LD A,(CURTRK)
	CP D		; compare track
	JP NZ,MINIR2	; -> track not equal, load sector
	
	LD A,(CURSEC)
	CP E		; compare sector
	JP NZ,MINIR2	; -> sector not equal, load sector

	; blocking / deblocking

MINIR1:	; actual physical sector is now in buffer PHSBUF

	CALL CALCPHS	; (PHSBUF+offset) -> DE, (IOD) -> HL, BC = 128
	EX DE,HL
	LDIR		; (DE++) <- (HL++), BC--
			; (IOD) <- (PHSBUF+offset), 128 Byte
	
	IF DEBOUT
	;LD A,0		; READ
	;CALL DEBBUF
	ENDIF

	XOR A
	RET		; -> finished without error

MINIR2:	; neuen Sektor laden, ggf. alten zurueckschreiben
	LD A,(BUFCHG)
	OR A
	JP Z,MINIR3

	CALL PUTPHS	; ALTEN ZURUECKSCHREIBEN
	JP C,ERRIO
	
MINIR3:	CALL MINCAL	; BERECHNEN

	LD A,C
	LD (CURDRV),A
	LD A,E
	LD (CURSEC),A
	LD A,D
	LD (CURTRK),A
	CALL GETPHS	; neuen Sektor lesen
	JP C,ERRIO	; Fehler aufgetreten
	
	JP MINIR1

;-----------------------------------------------------------------------------
; Write Mini disk
; BDOS-Flag in C

MINIWR:	LD A,C
	LD (ISDIR),A	; flag for Directory Write (1=write)

	CALL MINCAL	; calc physical sector and drive data for compare

	LD A,(CURDRV)	; und wie bei MINIRD
	CP C		;
	JP NZ,MINIW3	; other drive -> load sector

	LD A,(CURTRK)
	CP D
	JP NZ,MINIW3	; other track -> load sector

	LD A,(CURSEC)
	CP E
	JP NZ,MINIW3	; other sector -> load sector

	; blocking / deblocking
	
MINIW1:	; actual physical sector is now in PHSBUF

	CALL CALCPHS	; (PHSBUF+offset) -> DE, (IOD) -> HL, BC = 128
	LDIR		; (DE++) <- (HL++), BC--
			; (PHSBUF+Offset) <- (IOD), 128 Byte
	LD A,1
	LD (BUFCHG),A	; set buffer changed flag
	
	LD A,(ISDIR)
  	CP 1
	JP NZ,MINIW2	; -> no directory sector

	; directory sector: do not cache
	CALL PUTPHS 
	JP C,ERRIO	; if error then bad sector

MINIW2:	; -> finished without error
	XOR A
	RET

MINIW3:	; load new sector, write current if changed
	LD A,(BUFCHG)
	OR A
	JP Z,MINIW4
	
	CALL PUTPHS	; write current sector to disk
	JP C,ERRIO
	
MINIW4:	CALL MINCAL	; calc physical drive and sector data
	LD A,C
	LD (CURDRV),A
	LD A,E
	LD (CURSEC),A
	LD A,D
	LD (CURTRK),A
	CALL GETPHS
	JP C,ERRIO

	; no error
	JP MINIW1

;-----------------------------------------------------------------------------

ERRIO:	LD A,1	; Fehler aufgetreten
	OR A
	RET

;-----------------------------------------------------------------------------
; Calculates the pointer into PHSBUF based on sector number in IOS
; (PHSBUF + offset) -> DE
; (IOD) -> HL
; 128 -> BC (logical sector length)

CALCPHS:
	LD A,(BLMSK)
	LD B,A

	LD A,(IOS)	; logical sector number (0..n-1)
	AND B
	LD D,A		; load to high-byte (mul 256)
	LD E,0
	SRA D		; div/2 by shift right
	RR E
	; now we have (IOS mod SECSIZE) * 128 in DE
	LD HL,PHSBUF
	ADD HL,DE	; pointer into PHSBUF in DE
	
	IF DEBOUT
	;LD C,'['
	;CALL CONOUT
	;CALL DEBX16
	;LD C,']'
	;CALL CONOUT
	ENDIF
	
	EX DE,HL
	LD HL,(IOD)
	LD BC,128
	RET

	;LD HL,PHSBUF
	;LD A,(IOS)	; PHSBUF + ((0..39) MOD 8) * 128
	;AND 00000111b	; 0..7 (mod 8)
	;LD D,A		; * 256 (low byte is written into the high byte)
	;LD E,0
	;SRA D		; div/2 by shift right
	;RR E
	;ADD HL,DE	; HL = source (PHSBUF+offset)
	;EX DE,HL	; DE = source
	;LD HL,(IOD)	; HL = dest (IOD)
	;EX DE,HL	; DE = dest, HL = source
	;LD BC,128	; logical sector length
	;LDIR		; (DE++) <- (HL++), BC--
			; (IOD) <- (PHSBUF+offset), 128 Byte
	;XOR A
	;RET		; -> finished without error

;-----------------------------------------------------------------------------
; Read physical sector to PHSBUF
; Mini disk only
; TRKAKT,SEKAKT,DRVAKT ENTHALTEN NEUE BUFFERADRESSE

GETPHS:	; reset buffer changed flag
	XOR A		
	LD (BUFCHG),A

	LD HL,PHSBUF	; buffer address for data
	LD A,(CURSEC)
	LD E,A
	LD A,(CURDRV)	; bit0..3 and side in bit7
	LD C,A
	LD B,1		; 1 = read
	LD A,(CURTRK)
	LD D,A
	
	CALL FEXEC	; -> new floppy routine
	JP C,PHSERR

	IF DEBOUT
	CALL DEBPHY
	ENDIF
	
	; no error
	XOR A
	RET

;-----------------------------------------------------------------------------

PHSERR:	
	IF DEBOUT
	;LD C,'*'
	;CALL CONOUT
	ENDIF

	SCF
	RET

;-----------------------------------------------------------------------------
; Write PHSBUF to physical sector
; Mini disk only

PUTPHS:	; reset buffer changed flag
	XOR A
	LD (BUFCHG),A

	LD HL,PHSBUF	; buffer address
	LD A,(CURSEC)
	LD E,A
	LD A,(CURDRV)	; bit0..3 and side in bit7
	LD C,A
	LD B,2		; 2 = write
	LD A,(CURTRK)
	LD D,A

	IF DEBOUT
	CALL DEBPHY
	ENDIF
	
	CALL FEXEC	; -> new floppy routine
	JP C,PHSERR
	
	; no error
	XOR A
	RET

;-----------------------------------------------------------------------------

; Addresses of IDE-80 CF-Adapter card

IDEDATA	EQU 018h	; IDE Data Register
SECCND	EQU 01Ah	; Sector Count Register
LBA7	EQU 01Bh	; LBA Bits 0-7
LBA15	EQU 01Ch	; LBA Bits 8-15
LBA23	EQU 01Dh	; LBA Bits 16-23
IDEHEAD	EQU 01Eh	; IDE Drive Head Register
IDESTAT	EQU 01Fh	; IDE Command/Status Register

;-----------------------------------------------------------------------------

; Read one sector from disk.
; Return a 00h in A if the operation completes properly, and 01h if an error occurs during the read.
; Disk number in 'diskno' (4..7)
; Track number in 'track' (0..255)
; Sector number in 'sector' (0..63)
; DMA address in 'dmaad' (0-65535)
; 
; LBA
; 00000000 00000000 00000000
; 00000000 tttttttt ssssssdd
;        E        B        C

HSTBUF	EQU PHSBUF	; buffer for phyiscal sector
DISKNO	EQU DBANK
TRACK	EQU IOT
SECTOR	EQU IOS
DMAAD	EQU IOD

MIDERD	EQU 0F02Ah
MIDEWR	EQU 0F02Dh

IDERD:	LD HL,HSTBUF

	; LBA0..7 -> C
	LD A,(SECTOR)
	SLA A		; make room for 4 disks (0 to 3, 2 bits)
	SLA A
	LD B,A
	LD A,(DISKNO)
	SUB A,4
	OR B
	LD C,A		; C = sector * 4 + (diskno - 4)
	
	; LBA8..15 -> B
	LD A,(TRACK)
	LD B,A
	
	; LBA16..23) -> E
	LD E,0

	;LD A,'R'
	;CALL DEBIDE	; debug output
	CALL MIDERD
	
	IF FALSE

IDERD1:	; wait for not busy
	IN A,(IDESTAT)	; check status
	AND 80H		; check BSY bit
	JP NZ,IDERD	; -> wait

IDERD2:	; wait for ready
	IN A,(IDESTAT)	; check status
	AND 40H		; check DRDY bit
	JP Z,IDERD2	; -> wait
			
	LD A,01H	; number of sectors = 1
	OUT (SECCND),A	; sector count register
	LD A,(SECTOR)	; CP/M sector (0 to 63, 6 bits)
	SLA A		; make room for diskno (0 to 3, 2 bits)
	SLA A
	LD B,A
	LD A,(DISKNO)	; CP/M disk (0 to 3)
	ADD B		; diskno and sector now in one byte
	OUT (LBA7),A	; LBA bits 0 - 7
	LD A,(TRACK)	; CP/M track (0 to 255, 8 bits)
	OUT (LBA15),A	; LBA bits 8 - 15
	LD A,0		; upper bits zero
	OUT (LBA23),A	; LBA bits 16 - 23
	LD A,11100000B	; LBA mode, select host drive 0
	OUT (IDEHEAD),A	; drive/head register
	LD A,20H	; Read sector command
	OUT (IDESTAT),A
	
IDERD3:	; wait for DRQ
	IN A,(IDESTAT)	; read status
	AND 08H		; DRQ bit
	JP Z,IDERD3	; loop until bit set
			
IDERD4:	; wait for not busy
	IN A,(IDESTAT)
	AND 80H
	JP NZ,IDERD4	; -> wait

	IN A,(IDESTAT)	; clear INTRQ
	LD HL,HSTBUF	; buffer to place disk sector (256 bytes)

IDERD5:	IN A,(IDEDATA)	; get data
	LD (HL),A
	INC HL
	IN A,(IDESTAT)	; check status
	AND 08H		; DRQ bit
	JP NZ,IDERD5	; -> loop until clear

	ENDIF		; FALSE

	AND 01H
	RET NZ		; -> exit with error
			
	LD HL,(DMAAD)	; memory location to place data read from disk
	LD DE,HSTBUF	; host buffer

	LD B,128	; size of CP/M sector
IDERD6:	LD A,(DE)	; get byte from host buffer
	LD (HL),A	; put in memory
	INC HL
	INC DE
	DJNZ IDERD6	; put 128 bytes into memory

	;POP AF
	;IN A,(IDESTAT)	; get status
	;AND 01H		; error bit

	; no error
	XOR A
	RET

;-----------------------------------------------------------------------------

; Write one sector to disk.
; Return a 00h in register A if the operation completes properly, and 0lh if an error occurs during the read or write
; Disk number in 'diskno'
; Track number in 'track'
; Sector number in 'sector'
; DMA address in 'dmaad' (0-65535)

IDEWR:	LD HL,(DMAAD)	; memory location of data to write
	LD DE,HSTBUF	; host buffer
	LD B,128	; size of CP/M sector

IDEWR1:	LD A,(HL)	; get byte from memory
	LD (DE),A	; put in host buffer
	INC HL
	INC DE
	DJNZ IDEWR1	; put 128 bytes in host buffer

	LD HL,HSTBUF

	; LBA0..7 -> C
	LD A,(SECTOR)
	SLA A		; make room for 4 disks (0 to 3, 2 bits)
	SLA A
	LD B,A
	LD A,(DISKNO)
	SUB A,4
	OR B
	LD C,A		; C = sector * 4 + (diskno - 4)
	
	; LBA8..15 -> B
	LD A,(TRACK)
	LD B,A
	
	; LBA16..23) -> E
	LD E,0

	;LD A,'W'
	;CALL DEBIDE	; debug output
	CALL MIDEWR

	; status in A
	AND 01h		; notwendig ?
	RET


	IF FALSE

	LD HL,HSTBUF	; location of data to write to disk
IDEWR2:	IN A,(IDESTAT)	; check status
	AND 80H		; check BSY bit
	JP NZ,IDEWR2	; loop until not busy

IDEWR3:	IN A,(IDESTAT)	; check	status
	AND 40H		; check DRDY bit
	JP Z,IDEWR3	; loop until ready

	LD A,01H	; number of sectors = 1
	OUT (SECCND),A	; sector count register
	LD A,(SECTOR)	; CP/M sector (0 to 63, 6 bits)
	SLA A		; make room for diskno
	SLA A
	LD B,A
	LD A,(DISKNO)	; CP/M disk (0 to 3, two bits)
	ADD B		; diskno and sector in one byte
	OUT (LBA7),A	; LBA bits 0 - 7
	LD A,(TRACK)	; CP/M track (0 to 255, 8 bits)
	OUT (LBA15),A	; LBA bits 8 - 15
	LD A,0		; upper bits zero
	OUT (LBA23),A	; LBA bits 16 - 23
	LD A,11100000B	; LBA mode, select drive 0
	OUT (IDEHEAD),A	; drive/head register
	LD A,30H	; Write sector command
	OUT (IDESTAT),A

IDEWR4:	IN A,(IDESTAT)	; read status
	AND 08H		; DRQ bit
	JP Z,IDEWR4	; loop until bit set

IDEWR5:	LD A,(HL)
	OUT (IDEDATA),A	; write data
	INC HL
	IN A,(IDESTAT)	; read status
	AND 08H		; check DRQ bit
	JP NZ,IDEWR5	; write until bit cleared

IDEWR6:	IN A,(IDESTAT)
	AND 80H
	JP NZ,IDEWR6

	IN A,(IDESTAT)	; clear INTRQ
	AND 01H		; check for error
	RET

	ENDIF		; FALSE

;------------------------------------------------------------------------------
; Patch BDOS close function

	IF FALSE

PATFADR	EQU BDOSADR + 0CA8H

PATF:	LD IX,PATFADR
	LD A,(IX)
	CP 0C3h		; Z80 JP
	JR NZ,PATF1	; -> patch data does not match, do not patch

	LD A,LOW FLUSH
	LD (IX+1),A
	LD A,HIGH FLUSH
	LD (IX+2),A
	
PATF1:	RET
	ENDIF

;------------------------------------------------------------------------------
; Patch BDOS drive initialisation

PATAADR	EQU BDOSADR + 0C8CH
;BDPADR	EQU	0E043h
BDACT	DW 0			; BDOS active drive address

PATA:	LD IX,PATAADR
	LD A,(IX)
	CP 0AFh			; Z80 XOR A
	JR NZ,PATA1		; -> patch data does not match, do not patch
	
	LD A,(IX+1)
	CP 032h			; Z80 LD (abs),A
	JR NZ,PATA1		; -> patch data does not match, do not patch

	LD A,(IX+2)
	LD L,A
	LD A,(IX+3)
	LD H,A
	LD (BDACT),HL

	LD (IX+1),0CDh		; Z80 CALL
	LD (IX+2),LOW PATACL
	LD (IX+3),HIGH PATACL

	;LD C,'+'
	;CALL CONOUT

	;---------------------------------------------------------------------
	; BDOS patch: init BDOS active drive

PATACL:	LD HL,(BDACT)
	LD A,BTDRV
	LD (HL),A

	;PUSH BC
	;LD C,'!'
	;CALL CONOUT
	;LD A,(ACTIVE)
	;ADD '0'
	;LD C,A
	;CALL CONOUT
	;POP BC
	RET

PATA1:	;LD C,'-'
	;CALL CONOUT
	RET

;-----------------------------------------------------------------------------

	IF FALSE

PADBADR	EQU 0D75BH

PATB:	LD IX,PADBADR
	LD A,(IX)
	CP 03Ah			; Z80 LD A,(abs)
	JP NZ,PATB1		; -> patch data does not match, do not patch

	LD (IX+0),0CDh		; Z80 CALL
	LD (IX+1),LOW PATBCL
	LD (IX+2),HIGH PATBCL

	LD C,'*'
	CALL CONOUT

	;---------------------------------------------------------------------
	; BDOS patch

ACTIVE	EQU 0D744h

PATBCL:	LD C,'X'
	CALL 0F009H
	LD A,(ACTIVE)	
	PUSH AF
	ADD A,'0'
	LD C,A
	CALL 0F009H
	POP AF
	RET

PATB1:LD C,'-'
	CALL CONOUT
	RET

	ENDIF		; FALSE

;------------------------------------------------------------------------------

FEXEC:	JP 0F021h	; new Mini/Maxi routine

;=============================================================================
; Debuging routines

;-----------------------------------------------------------------------------
; Debug Read/Write physical sector
; B=1: read, B=2: write

	IF DEBOUT

DEBPHY:	LD A,(DEBACT)
	AND A,01H
	RET Z

	PUSH BC
	PUSH HL
	LD L,C		; save drive code
	
	LD C,'['
	CALL CONOUT
	LD C,'P'
	CALL CONOUT
	
	LD A,B
	;PUSH AF
	CP 1		; read
	JR NZ,DEBPH1	; -> write

	; read
	LD C,'R'
	JR DEBPH2

DEBPH1:	; write
	LD C,'W'

DEBPH2:	CALL CONOUT

	LD C,','
	CALL CONOUT

	; drive code in L
	LD A,L
	AND 10001111B
	;LD H,0
	CALL DEBX8

	LD C,','
	CALL CONOUT

	; track
	LD A,D
	CALL DEBX8

	LD C,','
	CALL CONOUT

	; sector
	LD A,E
	CALL DEBX8

	LD C,']'
	CALL CONOUT

	;POP AF
	;CP 1		; read
	;JR NZ,DEBPH3	; -> write

	; read
	CALL DEBLK

DEBPH3:	POP HL
	POP BC
	RET

	ENDIF

;-----------------------------------------------------------------------------

	IF DEBOUT

DEBLK:	PUSH DE

	LD C,'<'
	CALL CONOUT

	LD HL,PHSBUF
	LD B,8

DEBLK1:	; loop B=8..1
	LD A,(HL)
	CALL DEBX8
	LD C,'-'
	CALL CONOUT

	INC HL
	LD A,(HL)
	CALL DEBX8
	LD C,'-'
	CALL CONOUT
	
	INC HL
	LD A,(HL)
	CALL DEBX8
	LD C,','
	CALL CONOUT

	DEC HL
	DEC HL
	LD DE,80H
	ADD HL,DE
	DJNZ DEBLK1
	
	LD C,'>'
	CALL CONOUT

	POP DE
	
	RET

	ENDIF

;-----------------------------------------------------------------------------
; Debug output (DBANK) (READ/WRITE)

	IF FALSE

DEBDRV:	PUSH BC

	PUSH HL

	LD C,'['
	CALL CONOUT
	LD C,'F'
	CALL CONOUT
	LD A,(DBANK)
	LD L,A
	CALL DEBDEC
	LD H,0
	
	LD C,','
	CALL CONOUT
	POP HL
	CALL DEBDEC
	LD C,']'
	CALL CONOUT

	POP BC
	RET

	ENDIF

;-----------------------------------------------------------------------------
; Debug SELDRV

	IF FALSE

DEBSEL:	PUSH BC

	PUSH HL

	LD C,'['
	CALL CONOUT
	LD C,'S'
	CALL CONOUT
	LD A,(DBANK)
	LD L,A
	LD H,0
	CALL DEBDEC
	
	LD C,','
	CALL CONOUT
	POP HL
	CALL DEBDEC
	LD C,']'
	CALL CONOUT

	POP BC
	RET

	ENDIF

;-----------------------------------------------------------------------------
; Display drive, track, sector C,B,E

	IF FALSE

DEBIDE:	PUSH BC
	PUSH DE
	PUSH HL

	PUSH BC
	PUSH AF
	LD C,'['
	CALL CONOUT
	POP AF
	LD C,A
	CALL CONOUT
	LD C,' '
	CALL CONOUT
	LD C,'D'
	CALL CONOUT
	POP BC
	PUSH BC		; drive in C
	LD A,C
	AND 03H
	LD L,A
	LD H,0
	CALL DEBDEC

	LD C,','
	CALL CONOUT
	LD C,'S'
	CALL CONOUT
	POP BC		; sector in C
	SRL C
	SRL C
	LD L,C
	LD H,0
	CALL DEBDEC
	
	LD C,','
	CALL CONOUT
	LD C,'T'
	CALL CONOUT
	LD L,B
	LD H,0
	CALL DEBDEC

	;LD C,','
	;CALL CONOUT
	;LD C,'S'
	;CALL CONOUT
	;LD L,E
	;LD H,0
	;CALL DEBDEC

	LD C,']'
	CALL CONOUT

	POP HL
	POP DE
	POP BC
	RET

	ENDIF

;-----------------------------------------------------------------------------
; debug BDOS buffer, first 3 characters
; pointer in DMA, A=0: read, A=1: write

	IF FALSE

DEBBUF:	PUSH HL
	PUSH BC

	LD B,A		; read / write
	
	LD A,(DEBACT)
	AND A,01H
	JR Z,DEBBU3

	LD C,'['
	CALL CONOUT
	
	LD A,B		; read/write
	CP A,1		; -> write
	JP NZ,DEBBU1
	
	; read
	LD C,'R'
	JR DEBBU2

DEBBU1:	; write
	LD C,'W'

DEBBU2:	CALL CONOUT
	LD C,','
	CALL CONOUT
	
	LD HL,(IOD)
	
	LD A,(HL)
	CALL DEBX8	
	LD C,','
	CALL CONOUT

	INC HL
	LD A,(HL)
	CALL DEBX8	
	LD C,','
	CALL CONOUT

	INC HL
	LD A,(HL)
	CALL DEBX8	

	LD C,']'
	CALL CONOUT

DEBBU3:	POP BC
	POP HL
	RET

	ENDIF

;=============================================================================
; Debug outputs

	IF DEBOUT

;-----------------------------------------------------------------------------
; Display value in HL as decimal

DEBDEC:	PUSH AF
	PUSH BC

	LD BC,-10000	; 1. Zehnerpotenz: Zehntausender
	CALL DEBDE1
	LD BC,-1000	; 2. Zehnerpotenz: Tausender
	CALL DEBDE1
	LD BC,-100	; 3. Zehnerpotenz: Hunderter
	CALL DEBDE1
	LD BC,-10	; 4. Zehnerpotenz: Zehner
	CALL DEBDE1
	LD C,-1		; 5. Zehnerpotenz: Einer (immer ausgeben)
	CALL DEBDE1
	
	POP BC
	POP AF
	RET


DEBDE1:	LD A,'0' - 1	; Startwert fuer ASCII-Zeichen ('0' minus 1)

DEBDE2:	INC A		; Zeichen um 1 erhoehen (ASCII-Code weiterzaehlen)
	ADD HL,BC	; Zehnerpotenz abziehen
	JR C,DEBDE2	; Wenn kein Uebertrag (Zahl war groesser), weiter abziehen

	SBC HL,BC	; Uebertrag korrigieren (zu viel abgezogen, also wieder drauf)
    
	; Das Zeichen (ASCII-Code) befindet sich jetzt im Akkumulator (A).
	;PUSH BC	; Register sichern
	;PUSH HL
	LD C,A		; character to print
	CALL CONOUT	; uses A
	;POP HL
	;POP BC
	RET

;-----------------------------------------------------------------------------
; Output HL as 4-digit hex string

DEBX16:	PUSH AF

	LD A,H
	CALL DEBX8
	LD A,L
	CALL DEBX8
	
	POP AF
	RET

;-----------------------------------------------------------------------------
; Output A as 2-digit hex string

DEBX8:	PUSH AF
	PUSH BC

	PUSH AF
	SRL A
	SRL A
	SRL A
	SRL A
	CALL DEBXN
	POP AF
	CALL DEBXN

	POP BC
	POP AF
	RET

;-----------------------------------------------------------------------------
; Output low-nibble in A 1-digit hex string

DEBXN:	AND 0Fh
	CP 0Ah
	JR C,DEBXN1
	
	ADD A,'A'-10
	JR DEBXN2

DEBXN1:	ADD A,'0'

DEBXN2:	LD C,A
	JP CONOUT

;-----------------------------------------------------------------------------

	ENDIF	; DEBOUT

;=============================================================================

; data area

BUFCHG:	DB 0		; flag if PHSBUF is changed
CURDRV:	DB 0FFH		; DRIVE das geladen ist
CURDPB:	DW 0		; current disk parameter block
CURTRK:	DB 0		; TRACK 
CURSEC:	DB 0		; SEKTOR
ISDIR:	DB 0		; 1 = is directory write

DBANK:	DB 0		; disk bank (selected disk)

IOPB:	DW 1		; address of DPB of selected disk
IOT:	DB 4		; track number (offset des boot laufwerks???)
IOS:	DB 1		; NUMMER DES GEWUENSCHTEN SEKTORS
IOD:	DW BUFF		; DMA-ADRESSE
	
	; deblocking parameters for current drive
BLREG:	DB 1		; bits for special register (FLO+4)
BLPOW:	DB 1		; power (shift) value
BLMSK:	DB 1		; sector mask (modulo value)

	IF DEBOUT
DEBACT:	DB 0
	ENDIF

	;ENDEF		; end macro

	; floppy data area (from diskdef.lib)

BEGDAT	EQU	$
DIRBUF:	DS	128	;DIRECTORY ACCESS BUFFER

ALV0:	DS	49
CSV0:	DS	64

	IF NOT DG_BHD
ALV1:	DS	49
CSV1:	DS	64
	ELSE
	IF FALSE
;ALV1:	DS	45	;40	; 35
ALV1:	DS	40
CSV1:	DS	64
	ELSE
;ALV1:	DS	35	;37
ALV1:	DS	37
CSV1:	DS	64
	ENDIF
	ENDIF

	IF NOT DG_CHD
ALV2:	DS	49
CSV2:	DS	64
	ELSE
	; 1.44 MB
ALV2:	DS	45
CSV2:	DS	64
	ENDIF

ALV3:	DS	31
CSV3:	DS	16


ALV4:	DS	64	; size of each must be (DSM/8)+1
CSV4:	DS	0	; Could probably remove these chk areas, but just made size small
ALV5:	DS	64
CSV5:	DS	0
ALV6:	DS	64
CSV6:	DS	0
ALV7:	DS	64
CSV7:	DS	0
	
ENDDAT	EQU	$
DATSIZ	EQU	$-BEGDAT

ENDBIOS:

SIZE	EQU ENDBIOS-STARTBIOS

	END
	  
; END OF FILE
