;*****************************************************************************
; NPUTB-CF.Z80
;
; Write bootloader for MC CP/M-Computer IDE/CF drive

; based on BLOAD-CF von Ulrich Haumann from 05/2026
;
;*****************************************************************************
; Writes Boot loader from address 1000h to IDE/Compact-Flash
; Uses calls to Monitor and returns to Monitor
;
; DOES NOT USE BIOS or CP/M START ADDRESS !!!
;
; Writes track 0, sectors 0 
; Subroutine to write one IDE/ATA Disk sector (256 bytes)
; Address of data to write to disk passed in HL
; LBA bits 0 to 7 passed in C, bits 8 to 15 passed in B
; LBA bits 16 to 23 passed in E
;
; Version history
;
; 10.07.2026 *dg* Renamed to NBPUT-CF and reformatted
; 09.08.2026 *dg* Renamed to NPUTB-CF
;

;-----------------------------------------------------------------------------

BOOTADR	EQU 01000H	; the bootloader was loaded to this address before

; calls to Monitor
CONOUT	EQU 0F009h	; Output a chracter
IDEWR	EQU 0F02DH	; IDE/CF write routine in Monitor
MWARM	EQU 0F033H	; goto Monitor

BOOTDRV	EQU 4		; first IDE/CF-drive (only used for message)

;-----------------------------------------------------------------------------

	ORG 0100H	; start program here

START:	
	LD HL,MSG1
	CALL WRSTR

	LD HL,BOOTADR
	LD C,00H
	LD B,00H
	LD E,00H
	CALL IDEWR	; write one 128 byte sector
	
	LD HL,MSG2
	CALL WRSTR
	
	; we did not use the BIOS, so we can return to the Monitor
	JP MWARM

;-----------------------------------------------------------------------------
; Uses monitor CONOUT to print 0-terminated string
; address in HL
; 00h = string end

WRSTR:	LD A,(HL)	; get char from string
	AND A		; check if 0
	RET Z		; -> end of string
	
	LD C,A
	CALL CONOUT
	INC HL		; next char in string
	JP WRSTR	; start over

;-----------------------------------------------------------------------------

CR	EQU 0DH
LF	EQU 0AH

MSG1:	DEFB CR,LF,"NPUTB-CF V1.0 260809-01",CR,LF,0

MSG2:	DEFM "Bootloader written from 1000h to drive ",BOOTDRV+'A'," on IDE/CF",CR,LF,0

;-----------------------------------------------------------------------------

	END

;-----------------------------------------------------------------------------
